### PR TITLE
Make resamplers more flexible

### PR DESCRIPTION
**Pull request by zedxxx**

### CODE REVIEW

**Comment by andersmelander** [comment]
Please edit the description to explain:
- **What** problem does these changes solve.
- **How** does it solve them.
And since it seems that this will break a lot of existing code it better be good.

Also, are the changes in ´GR32_Polygons.pas´ related to the subject?

**Comment by zedxxx** [comment]
In our application we deal with a lot of small images and prefer to keep them in `PColor32Array` directly (we use a lightweight wrapper) instead of `TBitmap32`. But also we need to be able to draw this images into `TBitmap32`, so we need that at least two functions `StretchTransfer` and `BlockTransfer` could accept `Src` parameter as `PColor32Array`.

To solve this problem we need to add an overloaded versions of  `StretchTransfer` and `BlockTransfer` functions with low-level params. Unfortunately, `StretchTransfer` function make [this call](https://github.com/graphics32/graphics32/blob/master/Source/GR32_Resamplers.pas#L2484) of `TCustomResamplerAccess(Resampler).Resample` which brings us to that we need to modify method `TCustomResampler.Resample` to accept low-level params too. But this shouldn’t break any existing GR32 code or I'm wrong?

About `GR32_Polygons.pas` you are right - this is another improvement but it is not related to the subject. I will rollback changes in this unit and make a new PR.

**Comment by zedxxx** [comment]
Oh, I think that I understand how this PR can break existing code. I will update PR tomorrow with backward compatibility fix.

**Comment by zedxxx** [comment]
Done.

**Comment by andersmelander** [comment]
Your changes looks good in isolation but I'm inclined to reject them due to the significant overhead (code, not performance) they add and the amount of existing code they will break.
More importantly, as far as I can tell the problem they address could be easily solved in a non-breaking way by wrapping your PColor32Array in a custom backend. Something like this:
```
type
  TMyBackend = class(TCustomBackend)
  public
    constructor Create(Owner: TCustomBitmap32; ABits: PColor32Array); reintroduce;
  end;

constructor TMyBackend.Create(Owner: TCustomBitmap32; ABits: PColor32Array);
begin
  inherited Create(Owner);
  FBits := ABits;
end;

begin
  var Bitmap := TBitmap32.Create(Width, Height)
  TMyBackend.Create(Bitmap, MyBits);
  ... business as usual...
end;
```

Please reopen the PR if you disagree.

**Comment by zedxxx** [comment]
@andersmelander 

Why do you think that this PR brakes some existing code? It doesn't change existing functions but only add overloaded versions of them. If I misunderstand something, tell me and I will try to fix it.

I don't understand how I can use your example to draw `PColor32Array`, but if you telling about *wrapping*, I know that I can wrap `PColor32Array` with `TCustomBitmap32` and use existing `StretchTransfer` function, but this forces me to use temporary object **every time** I want to call `StretchTransfer` (this happens quite often). So, this PR provides overloaded version of `StretchTransfer` that will accept `PColor32Array` as `Src` and temporary object is no longer needed.

**Comment by andersmelander** [comment]
@zedxxx Resamplers derived from `TCustomResampler` will break since the old `Resample` method is no longer virtual and the new, virtual one has a different signature.

Yes, it's true that you will need to create a `TBitmap32` (and a custom backend) in order to wrap your `PColor32Array` and I can understand if you don't like this overhead, but that can be worked around. For example create a single global wrapper and reuse that for your `StretchTransfer` calls. I don't know your code but it might also be possible to replace your `PColor32Array` with a `TBitmap32` using a `TMemoryBackend`.
I understand that this isn't as desirable a solution from your POW but from my POW it's better than obfuscating the graphics32 code for every one else.

**Comment by zedxxx** [comment]
Ok.

**Pull request closed without merging**
