### PR TITLE
TImage32/TImgView32 background, pan & zoom

### PR DESCRIPTION
**Pull request by andersmelander**

### CODE REVIEW

**Comment by riaanjutte** [comment]
Hi Mr. Melander, please forgive me for asking you a question out of the blue. I am currently attempting to add support for pan & zoom of a map viewer tool I'm writing, and I'm struggling with adding pan support in that the image gets corrupted. Does this pull request address this issue? Or is there an example of how to implement pan & zoom for the TImgView32 component?
Thanks! 
Adriaan Jutte

**Comment by andersmelander** [comment]
> Does this pull request address this issue?

Yes, it should.

> is there an example of how to implement pan & zoom for the TImgView32 component?

See the "Examples\General\Pan & Zoom" example.

**Comment by riaanjutte** [comment]
Works perfectly after pulling the image32_background tree, thanks 👍

**Comment by andersmelander** [comment]
That's great. Let me know if there are any problems with the feature.

**Pull request merged**
