### PR TITLE
Add TCustomBitmap32.Ellipse and FillEllipse

### PR DESCRIPTION
**Pull request by gonutz**
This adds Ellipse and FillEllipse in the regular, T, S and TS versions for issue #157.

There is also a new unit test project under `Tests/EllipseTests`. All 8 functions are tested and benchmarked. The code is not the prettiest, but I made it as fast as I could while keeping the tests happy. I am using Delphi XE4 in 32 bit mode. There is a batch script to run the tests in that folder and maybe people can run the benchmarks on other compilers. I would be interested in their results. Here are mine:

```
FillRect took 30 ms
FillEllipse took 46 ms
FillEllipseT took 240 ms
FillEllipseS took 57 ms
FillEllipseTS took 288 ms
TCavas32.Ellipse took 633 ms
Large Ellipse took 25 ms
Ellipse took 26 ms
EllipseT took 40 ms
EllipseS took 34 ms
EllipseTS took 50 ms
```

I am putting this out there now so that it is visible to people to try. I ask you to poke at it a little more to see where it breaks down so I can add more tests and get it working well.

There is still a difference between the 4 FillEllipse and the 4 Ellipse functions. The FillEllipse functions have the algorithm inlined, there is a lot of duplicated code. For the Ellipse functions I used a helper struct and inlined helper methods to get rid of some of the duplication. This makes the code more readable in my opinion, while not making the benchmarks any slower. Now I saw that there is a compiler flag `USEINLINING` that seems to surround `inline` directives around public functions. I use `inline` on my private methods to keep the code fast. Is this style in line with your preferences for this library? If I can get a little feedback on this subject, I would like to refactor the code to make the functions be structured similarly. The question is just which way is preferred.

Also, what else would you like to change style wise? I used the FillRect functions for reference of how to lay out the code so I hope it is quite in line with the rest already but then it is a lot of code so please give me your suggestions as how to further improve it.

### CODE REVIEW

**Comment by gonutz** [comment]
@graphics32 @andersmelander @evilJazz @meanderix @Mhbuur @micha137

Hey there, any updates on this PR?
I have used it for my use case at work this week and it does its job.
I know time is sparse but I would really appreciate feedback on this.

**Comment by andersmelander** [comment]
I _have_ looked at it but I just don't have time to comment on it right now. I'll try to find time this week-end.
P.S. Don't @mention people unless there's a relevant reason to (and your desires aren't). You will just piss them off.

**Comment by gonutz** [comment]
Nice, thanks for the update. As I said, I know about time being a constrained resource.

Regarding your PS, I see you are annoyed. Please do not be. There is no need to use profanity. Also do not try to attack me. My desires are relevant indeed. Let me give advice back: try to be more empathetic. Try to understand that I have not gotten a reaction on this thing, that I put a lot of work into, for over a week. Instead, next time someone sends in a PR, just let them know you are busy right now and that it will take a little time.

**Comment by JSchrtke** [comment]
Any updates on this?

**Comment by gonutz** [comment]
Since this repo seems only semi-actively maintained, I will keep working on my own fork and use that instead. Thanks for the great work you did, this library is very useful, I really appreciate you putting this out there for free :-)

I will leave the PR open if anybody is still interested.

**Comment by andersmelander** [comment]
First of all your code seems well written and is nicely formatted.

It would have been interesting to have it benchmarked against the existing Graphics32 ellipse functions instead of GDI which we already know is slow :-)

I have the following comments to your PR:

1. Until we declare V2 released we will unfortunately have to maintain backward compatibility with Delphi 7. This means no "modern" language features such as inline (without the `USEINLINING` conditional) or record methods.
Yes, it's a bore and if I had the time I would do it right this moment, but unfortunately I don't have time.
If you don't want to bother with trying to make the code backward compatible (which I perfectly understand) you can either simply disable all the ellipse code via a conditional for older compilers - or you can leave it in a branch. We already have a couple of branches with code that isn't backward compatible.

2. Please do not include unrelated changes in the PR.
While I agree that the `AREAINFO_ELLIPSE` constant should be deleted, the removal does not belong in this PR - even though both has to do with ellipses.

3. The ellipse implementation should be moved out of `TCustomBitmap32`.
`TCustomBitmap32` is fat enough as is and we should try to avoid this monolithic design of adding non-core features to it. It would be better to implement a TEllipse32 class (or even a record with methods) in a separate unit. This also solves the backward-compatible problem.

4. There are far to few comments explaining what's going on.
I think I counted 3 comments...

5. The T variants need to handle gamma.
See the LineT variants for examples of how to do that.

6. I think it is a problem that you haven't implemented anti-aliased variants.
While I have understood that _you_ don't need anti-aliasing it _is_ a fairly common feature and the lack of AA would make it the only graphics primitive with this omission.
That said, if the code was commented so others could add AA variants, and it was moved to a separate unit, I don't see an immediate problem with your non-AA specializations.

**Comment by gonutz** [comment]
Hey, thanks for getting back at me!

What do you mean by benchmarking against GDI? I did not even take the time to do that, as I know the result as well without trying ;-)
The `TCavas32.Ellipse` in my first comment here is using the Canvas32 Ellipse which calls `TCustomPath.Ellipse` which draws a `Polygon` using `GR32_VectorUtils.Ellipse`. There is no GDI benchmark in my code, or does anything there use GDI?

To quickly address the other points:

1. I fully understand your desire to be backward compatible. I was wondering about the `USEINLINE`s. I only have Delphi XE4 available to me. I would love to have the oldest and latest supported versions to test against but since they are not free, this is kind of complicated :-)
2. Yes sure, they are not really related but then removing it does not cause much harm in my opinion since it is never used anyway. As I said, I was at first wondering whether I should use it so it actually is kind of related.
3. Interesting rationale, I was actually wondering why some functions are methods of the bitmap and some are placed in other units. I prefer the straight forward approach to things, it has served me much better than fancy architectures and drawing from my experience I think putting the methods inside the bitmap is actually better than extracting it. Advantages include
3.1. simply being able to type `Bitmap.` and let the IDE auto-complete me a list of available drawing functions
3.2. find all the code in one place
3.3 not needing to make things public just to be able to have other units access them
I also have nothing against large classes per se. I think the `TCustomBitmap32` is fine the way it is. I see the points against it but in my opinion pros outweigh cons in this case, I would place new drawing functions there.
4. You are right, there should be a number of comments explaining the use of the ellipse helper records, how they are set up and how they are stepped, with a link to the paper containing the original code, there should be comments for those inline methods and why the design is like it is (keeping a balance between readable code and speed). I definitely need to do that.
5. Oh, I see now. I was actually looking at `FillRectT` for reference. Why does it not use the `BlendProc` and how does that differ from the `CombineMode` with `CombineMem` and `MergeMem`?
6. Am I misunderstanding this (see above) but the `TCanvas32.Ellipse` is anti-aliased, is it not? So there is an AA version of the ellipse, I set out to make a non-AA version. I know these are in different places with different APIs, one in the bitmap as a method, the other in another class, but having an ellipse in `A`, `X` and `P` variants would re-implement that functionality, right?

**Comment by andersmelander** [comment]
Re: benchmark: My bad. I misread your first comment.

1. I personally have no desire to be backward compatible with versions before XE but until we announce that the older versions of Delphi are no longer supported, we kinda have to support them. There's also FPC compatibility to consider, which is difficult since there are no active contributors using it.
2. It's not that important in this case. It's more of a general principle that a commit (or a PR) should never include changes related to more than a single issue.
3. I agree that it's convenient to have auto complete find the methods. Beyond that nope. Graphics32 is a large'ish library and a monolithic design will not make it easier to maintain or extend. Imagine if we moved every function that operate on `TCustomBitmap32` into that class. It would become a big ball of mud.
4.  - 
5. There's no difference and you can use either methods as it suits you. My guess is that `BlendProc` was introduced after `FillRectT` was written.
6. Yes `TCanvas32.Ellipse` is anti-aliased. In theory it is possible to use a polygon renderer that doesn't do AA but I don't think we have one of those.
The problem here isn't duplication but more that your ellipse uses a completely different algorithm and is optimized for a very narrow range of parameters (for example the outline width, stroke and fill type). `TCanvas32.Ellipse` and your Ellipse can't really be said to be different variants of the same primitive, just like `TCanvas32.Rectangle` isn't a variant of `TCustomBitmap32.FrameRect*`

**Comment by andersmelander** [comment]
Won't do; Bad fit

**Pull request closed without merging**
