### PR TITLE
[Bug Fix] Do not define SSE2 and SSE4.1-specific procedures in PUREPASCAL mode

### PR DESCRIPTION
**Pull request by CuriousKit**
This pull request surrounds SSE-specific FastTrunc and FastRound routines with {$IFNDEF PUREPASCAL} directives so they are not defined under "Pure Pascal" mode.  This is so assembler errors are not generated when compiling Graphics32 on non-Intel platforms (e.g. AArch64), since the Intel-specific mnemonics and registers are unrecognised outside of i386 and x86_64.

(Some additional work is needed to get it to compile under aarch64-linux (in this case, a Raspberry Pi), but this is one of the more glaring problems)

### CODE REVIEW

**Comment by CuriousKit** [comment]
No problem @andersmelander.  Internal errors are not good though (automatic bug).  There have been some teething problems with checksums with FPC lately, although my focus is on optimisation.  FPC 3.2.2 fix a number of issues over FPC 3.2.0, so see if that helps at all.

**Comment by andersmelander** [comment]
The problems started when I upgraded from Lazarus 2.2.6 (FPC 3.2.2) to Lazarus 3.2 (FPC 3.2.2) so the problems appears to be Lazarus and not FPC.

**Comment by CuriousKit** [comment]
Oh right, hmmm.  All I can really suggest is to file a bug report on the Lazarus gitlab page, but errors that don't have a consistent means of generation are infamously hard to track down.

**Comment by andersmelander** [comment]
Oh it's easy enough to reproduce consistently. It's just that, from what I've seen of others that get this problem, the suggested solution from the Lazarus devs is to reorganize the source or not use inlining in the units where the problem occurs; The problem is apparently caused by the way FPC implements inlining and the attitude appears to be that it's "as-designed".

Anyway, I'm curious about how you can use GR32 on a Raspberry Pi. What output device do you have available?

**Comment by CuriousKit** [comment]
Aah, yeah, inlining is an interesting one.  The main rule is to make sure the "inline" directive appears in the interface section of a function declaration, and not just the implementation section.

Currently GR32 doesn't compile on the Raspberry Pi because TLCLBackend in GR32_Backends_LCL_Gtk is missing its "InvalidateRect" method.  My output device is a micro-HDMI to a standard monitor.

My intention is to help get the project "NeoLemmix" to work under Arm-64 platforms.

(Also is there a better place to talk than this comments section?)

**Comment by andersmelander** [comment]
As far as I can tell all inline functions that are declared in the interface all have their "inlineness" declared there as well. There are a few inline functions that are only declared in the implementation section so naturally those can't be declared inline in the interface.
No, the problem appears to be that when rebuilding Lazarus, it compiles some units twice and apparently changes the compiler options between first and second compile. The reason it tries to compile it twice is probably that the checksum changes because of the option change. It's not because I have the source in multiple places or something like that.

> Currently GR32 doesn't compile on the Raspberry Pi because TLCLBackend in GR32_Backends_LCL_Gtk is missing its "InvalidateRect" method. My output device is a micro-HDMI to a standard monitor.

You can try out the [FPC_GTK branch](https://github.com/graphics32/graphics32/tree/FPC_GTK). I don't have a Linux system so the solution in it is based purely on guesses and it would be a miracle if it worked - but you never know :-)

> (Also is there a better place to talk than this comments section?)

Yes, there is the [Discussion section](https://github.com/graphics32/graphics32/discussions). Unfortunately I can't _move_ this comment thread there. That is only possible on issue threads.

**Comment by CuriousKit** [comment]
I do recall a number of threads on the FPC mailing lists about problems with units compiling out of order and checksum problems etc.  I think they're trying to get that resolved for the next release.  Inlining is unfortunately a bit of a sour topic it seems.

My ambition is to start writing Arm-64 assembly routines to get the speed boosts required for NeoLemmix to run on a Raspberry Pi (the reason why the creator hasn't gone that way yet).  I'll see if there's places where the x86 assembly language can be improved too.  I can see though that many of the x86_64 assembly routines will need to be adapted for non-Windows platforms because of the different callilng convention (e.g. the first integer parameter is in RDI, not RCX).

I'll start up some discussions soon... if getting Graphics32 to work well under aarch64-linux and x86_64-linux is an acceptable target.

(Running the tests might be a bit tricky because FPC doesn't have the "TestFramework", "GUITestRunner" and "TextTestRunner" units)

**Comment by andersmelander** [comment]
NeoLemmix... Interesting!

>  if getting Graphics32 to work well under aarch64-linux and x86_64-linux is an acceptable target.

That's up to you; If you need it then it's acceptable. I'll assist where I can.

Wrt. unit tests I think LCL might have something DUnit compatible; I seem to remember seeing some {$ifdef FPC} in one of the unit test projects. I'll look into it once I get the Lazarus installation problem resolved.

**Pull request merged**
