### PR TITLE
1.9.1: fixes and additions

### PR DESCRIPTION
**Pull request by idanmiara**
Hi,

I know it's an old branch, but my app is incompatible with the master branch.
Please merge my fixes and minor additions.

Please note that "Graphics32_1.9.1_Fixes" is also a name of a tag based on an older commit on this branch. Please consider renaming either to avoid confusion.

Kind Regards,
Idan.

### CODE REVIEW

**Comment by CWBudde** [comment]
Yes, this project and branch is still maintained to a certain degree.
However, in the past we always took some effort to ensure that everything works as intended. This should be our effort here as well. Unfortunately, I don't have time at the moment and probably others don't have the time either at the moment. Especially, since most of our projects already base on the latest version.

I'll leave it for the weekend to downgrade and test your changes. Hopefully I can merge the changes quickly then.

**Comment by imiara** [comment]
OK, Thanks for your answer!

**Comment by CWBudde** [comment]
I have looked through it and it seems to be OK. However, there are still a few things I want to test/check before I am OK to merge it.

Eventually I'd like to split this into two merges in order to already merge the accepted changes as soon as possible. Unfortunately, I am too tired to do this right now. I'll have a look at it once I have some more spare time.

**Comment by imiara** [comment]
Thanks!

**Pull request closed without merging**
